### PR TITLE
Instantiating lxc class instead of calling container method

### PR DESCRIPTION
**Pull request by rizvfe00**
This resolves the missing method error for ruby 2.0

### CODE REVIEW

**Comment by rizvfe00** [comment]
The error on the failing build looks like a build config issue.  Let me know if you need anything from me.

**Comment by eheydrick** [comment]
It's failing on Ruby 1.9.3 due to net-ssh requiring ruby 2+ now. We're going to drop 1.9.3 support in February but I think we should drop it early for these plugins.

**Comment by mattyjones** [comment]
@eheydrick  I agree as well. I will leave it up to you if you want to merge this.

**Comment by Qsick** [comment]
Can this PR be merged now that 1.9.3 support has been dropped?

**Comment by Qsick** [comment]
@mattyjones @eheydrick Can this PR be merged now that 1.9.3 support has been dropped?

**Comment by eheydrick** [comment]
Yes, I'm pulling the change in and will release it soon.

**Comment by eheydrick** [comment]
Manually merged and released in 1.0.0. Fixes #1

**Comment by Qsick** [comment]
👍

**Pull request closed without merging**
